server:
  port: 9999
spring:
  application:
    name: microservice-consumer-ccb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000